name = "ModelingToolkitJoysticks"
uuid = "7e02f2af-d440-4c08-8401-b0517a24ed29"
authors = ["Ben Chung <ckfinite@gmail.com>"]
version = "0.1.0"

[deps]
GLFW = "f7f18e0c-5ee9-5ccd-a5bf-e8befd85ed98"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
GLFW = "3.4.3"
ModelingToolkit = "9.63.0"
Symbolics = "6.29.0"
OrdinaryDiffEqTsit5 = "1.1.0"

[extras]
OrdinaryDiffEqTsit5 = "b1df2697-797e-41e3-8120-5422d3b24e4a"

[targets]
test = ["Test", "OrdinaryDiffEqTsit5"]
